### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by harshad16** [thoth-station/package-update-job#187]
**Describe the bug**
```
[2021-02-08 18:22:00,537] [1] [ERROR] [^Worker]: Error: AttributeError("can't set attribute",)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1073, in on_start
    await self._fut
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 598, in execute
    await self.run(*args, **kwargs)
  File "/opt/app-root/src/producer.py", line 178, in main
    graph.connect()
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 291, in connect
    if not database_exists(self._engine.url):
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres_utils.py", line 79, in database_exists
    database, url.database = url.database, os.getenv('KNOWLEDGE_GRAPH_DATABASE')
AttributeError: can't set attribute
[2021-02-08 18:22:00,585] [1] [ERROR] [^Worker]: Error while stopping child <main: stopping >: AttributeError("can't set attribute",)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 863, in _default_stop_children
    await asyncio.shield(child.stop())
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 839, in stop
    await self.on_stop()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1084, in on_stop
    fut.result()
  File "/opt/app-root/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 1073, in on_start
    await self._fut
  File "/opt/app-root/lib/python3.6/site-packages/faust/cli/base.py", line 598, in execute
    await self.run(*args, **kwargs)
  File "/opt/app-root/src/producer.py", line 178, in main
    graph.connect()
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres.py", line 291, in connect
    if not database_exists(self._engine.url):
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/graph/postgres_utils.py", line 79, in database_exists
    database, url.database = url.database, os.getenv('KNOWLEDGE_GRAPH_DATABASE')
AttributeError: can't set attribute
 ```
This issue was observed in stage and test clusters.
Package-update-job version: **v0.8.4**

**Comment by harshad16** [comment]
Package-update job is failing in the stage and test

**Comment by fridex** [comment]
It is not clear to me what's happening based on backtrace provided. It is probably trimmed?

**Comment by harshad16** [comment]
yes frido, it is trimmed, i just opened this for not forgetting.
i will add more details in this issue now .

**Comment by harshad16** [comment]
This seems very strange, only package-update job storage component is not able to connect to the graph database.
all the env vars are set properly.

**Comment by fridex** [comment]
Not online so hard to check this, but do we still use `KNOWLEDGE_GRAPH_DATABASE` (based on the backtrace)?

**Comment by harshad16** [comment]
> Not online so hard to check this, but do we still use `KNOWLEDGE_GRAPH_DATABASE` (based on the backtrace)?

yes we do. 
i wanted to check this on a newer image, also as we have updated python and messaging. 
and trying fix an newer version would be better then old version

**Comment by harshad16** [comment]
This was fixed with referenced PR's
thank you for the work.
closing the issue.
